export const DAILY_REFLECTIONS_EN: Record<string, string[]> = {
  early_life: [
    "Describe the house you grew up in. Not what it looked like — what it smelled like on a normal Tuesday morning.",
    "What was the view from your childhood bedroom window?",
    "What did your family eat for breakfast when you were young? Who cooked it?",
    "What was the walk to school like? What do you remember most about it?",
    "Who was your best friend when you were ten years old? What did you do together?",
    "What did your father's hands look like? What do you remember about them?",
    "What was the first job you ever had? How much did you earn?",
    "What music was playing in your home when you were growing up?",
    "What was the hardest thing about being young that nobody talked about?",
    "Describe a meal that takes you back to your childhood instantly.",
  ],

  relationship_to_family: [
    "What is something your mother did that you only understood after you became a parent yourself?",
    "What did your father teach you without ever sitting down to teach it?",
    "Describe the moment you knew your spouse was the right person.",
    "What is the most important thing you want your grandchildren to know about your family?",
    "What family tradition matters most to you and how did it start?",
    "Who in your family are you most like and who are you most different from?",
    "What is something you wish you had said to a family member who is no longer here?",
    "Describe a moment when your child surprised you completely.",
    "What does home mean to you?",
    "What is the best advice your parents ever gave you?",
  ],

  defining_experiences: [
    "What is the single day in your life you would most want to live again?",
    "Describe the moment everything changed. Not a big public event — the quiet moment that shifted everything.",
    "What is something you survived that you did not think you would survive?",
    "What risk did you take that changed your life?",
    "What was the hardest year of your life and what got you through it?",
    "Describe a journey you took — physical or otherwise — that changed who you are.",
    "What is something you built from nothing that you are proud of?",
    "What opportunity did you almost miss and what happened when you took it?",
    "Describe the day you arrived somewhere new for the first time.",
    "What decision are you most grateful you made?",
  ],

  professional_philosophy: [
    "What was the best job you ever had and what made it meaningful?",
    "Who taught you how to work? What did they show you?",
    "What is the hardest professional situation you ever faced?",
    "What do you know about money that took you decades to learn?",
    "Describe a time you failed at something important. What happened next?",
    "What did success look like when you were young versus now?",
    "What is the most important thing you built in your career?",
    "Who was the most difficult person you ever worked with?",
    "What advice would you give someone starting their career today?",
    "What did work teach you about life?",
  ],

  core_values: [
    "What is something you believe that most people around you do not?",
    "Describe a time you did the right thing when it cost you something.",
    "What line have you never crossed — not because you were told not to but because you simply could not?",
    "What does integrity mean to you in your daily life?",
    "What value did you learn from your parents that you still carry?",
    "When have you been most proud of yourself?",
    "What do you believe about how to treat people?",
    "What would you never compromise on?",
    "What has life taught you about what truly matters?",
    "What do you want to be remembered for?",
  ],

  wisdom_and_lessons: [
    "What is the best advice you ever received and who gave it?",
    "What do you know now that you wish you had known at 25?",
    "What mistake do you see young people make that you learned to avoid?",
    "What has surprised you most about getting older?",
    "What is something that seemed important when you were young that does not matter at all now?",
    "What is the most valuable thing you own that has no monetary value?",
    "What would you tell your 20-year-old self?",
    "What have you changed your mind about as you have gotten older?",
    "What is the secret to a long and happy life?",
    "What do you want your grandchildren to understand about how to live?",
  ],

  approach_to_people: [
    "Who is the most interesting person you have ever met? What made them interesting?",
    "Describe a friendship that changed your life.",
    "What do you look for in a person to know if they can be trusted?",
    "Who was the kindest person you ever knew?",
    "Describe someone who believed in you when no one else did.",
    "What did you learn about people the hard way?",
    "Who has influenced you most outside of your family?",
    "What makes a good neighbor?",
    "Describe a stranger who did something that stayed with you.",
    "What do you know about human nature that took decades to understand?",
  ],

  approach_to_money: [
    "What was the first thing you ever saved up to buy?",
    "Describe a time when you had very little money. How did you manage?",
    "What is the best financial decision you ever made?",
    "What did your parents teach you about money?",
    "What does financial security mean to you?",
    "What would you do differently with money if you could start over?",
    "What is something money cannot buy that you have learned to value?",
    "What is the most important thing you have done for your family's financial future?",
    "What do you wish you had invested in earlier?",
    "What does generosity mean to you?",
  ],

  spiritual_beliefs: [
    "What do you believe happens after we die?",
    "Describe a moment when you felt something greater than yourself.",
    "What gives your life meaning?",
    "How has your faith or spirituality changed across your life?",
    "What prayer or saying has carried you through hard times?",
    "What do you believe about why we are here?",
    "Describe a time you experienced something you could not explain.",
    "What spiritual practice or belief has helped you most?",
    "What do you want your grandchildren to know about your faith?",
    "What has suffering taught you about meaning?",
  ],

  fears_and_vulnerabilities: [
    "What are you most afraid of and how do you face it?",
    "Describe a time you were genuinely terrified.",
    "What have you had to be brave about that others might not know?",
    "What keeps you up at night?",
    "What do you worry about for the next generation?",
    "What have you had to forgive yourself for?",
    "What is something you have never talked about that you carry quietly?",
    "What does vulnerability mean to you?",
    "When have you felt most alone and what helped?",
    "What would you want people to know about your struggles?",
  ],
}

export const DAILY_REFLECTIONS_ZH: Record<string, string[]> = {
  early_life: [
    "描述一下您小时候住的房子。不是它的外观——而是在一个普通的周二早晨，那里是什么气味？",
    "您童年卧室窗外的景色是什么样的？",
    "您小时候家里早餐吃什么？是谁做的饭？",
    "您上学路上是什么样的？您记忆最深的是什么？",
    "您十岁时最好的朋友是谁？你们在一起做什么？",
    "您父亲的双手是什么样的？您对它们有什么印象？",
    "您做的第一份工作是什么？挣了多少钱？",
    "您成长过程中，家里经常放什么音乐？",
    "年轻时最难熬却无人诉说的事是什么？",
    "哪一道菜能立刻把您带回童年？",
  ],

  relationship_to_family: [
    "您母亲做的哪件事，是您自己为人父母后才真正理解的？",
    "您父亲在没有刻意教导的情况下，教会了您什么？",
    "描述一下您意识到另一半是对的人的那个时刻。",
    "您最希望孙子孙女们了解您家庭的哪一件事？",
    "对您来说最重要的家庭传统是什么？它是怎么开始的？",
    "家族中，您最像谁，又与谁最不同？",
    "有没有一句话，是您希望曾经对一位已故亲人说过的？",
    "描述一个让您完全出乎意料的、孩子令您惊喜的时刻。",
    "家对您意味着什么？",
    "父母给您的最好建议是什么？",
  ],

  defining_experiences: [
    "您一生中最想重新经历的一天是哪一天？",
    "描述一下改变了一切的那个时刻。不是大事件——而是那个悄悄改变了一切的平静时刻。",
    "描述一件您以为自己撑不过去、但最终挺过来的事。",
    "您冒过的最大的险，它如何改变了您的生活？",
    "您人生中最艰难的一年是哪一年？是什么帮您度过了那段时光？",
    "描述一次改变了您的旅程——无论是身体上还是心灵上的。",
    "您从零开始建立起来的、让您最感到自豪的是什么？",
    "您差点错过的一个机会是什么？当您抓住它时发生了什么？",
    "描述您第一次来到一个陌生地方的那一天。",
    "您最庆幸做出的一个决定是什么？",
  ],

  professional_philosophy: [
    "您做过的最好的工作是什么？是什么让它有意义？",
    "谁教会了您如何工作？他们教了您什么？",
    "您职业生涯中面临的最困难的处境是什么？",
    "关于金钱，您花了几十年才明白的最重要的事是什么？",
    "描述一次重要的失败。之后发生了什么？",
    "年轻时的成功与现在的成功，在您眼中有什么不同？",
    "您职业生涯中最重要的成就是什么？",
    "您共事过的最难相处的人是谁？",
    "您会给今天刚踏入职场的人什么建议？",
    "工作教会了您关于人生的什么？",
  ],

  core_values: [
    "您持有一种周围大多数人不认同的信念是什么？",
    "描述一次您做了正确的事，但为此付出了代价的经历。",
    "有一条底线是您从未逾越的——不是因为被告知不能，而是您内心就是做不到——那是什么？",
    "诚信在您日常生活中意味着什么？",
    "父母传递给您的哪种价值观，您至今仍然珍视？",
    "您什么时候最为自己感到骄傲？",
    "您信奉怎样的待人之道？",
    "有什么是您绝对不会妥协的？",
    "生活教会您什么才是真正重要的？",
    "您希望被人们如何记住？",
  ],

  wisdom_and_lessons: [
    "您收到过的最好的建议是什么？是谁给您的？",
    "如果您能回到25岁，最想告诉自己什么？",
    "您看到年轻人常犯什么错误，而您已经学会了避免？",
    "变老最让您感到意外的是什么？",
    "年轻时觉得很重要的事，现在看来根本无所谓的是什么？",
    "您拥有的最有价值的东西，但没有金钱价值的是什么？",
    "您会对20岁的自己说什么？",
    "随着年龄增长，您改变了哪些看法？",
    "长寿又幸福的秘诀是什么？",
    "您希望孙子孙女们明白的人生道理是什么？",
  ],

  approach_to_people: [
    "您遇到过最有趣的人是谁？是什么让他们与众不同？",
    "描述一段改变了您人生的友谊。",
    "您如何判断一个人是否值得信任？",
    "您认识的最善良的人是谁？",
    "描述一个在别人都不相信您时相信您的人。",
    "您吃过最大的亏，是在识人方面吗？那是什么教训？",
    "在家人之外，谁对您影响最大？",
    "什么样的人才算好邻居？",
    "描述一个素不相识的人，他/她做了一件让您铭记至今的事。",
    "关于人性，您花了几十年才明白的是什么？",
  ],

  approach_to_money: [
    "您人生中第一次存钱买的东西是什么？",
    "描述一段您手头很紧的时光。您是怎么撑过来的？",
    "您做过的最好的财务决定是什么？",
    "您的父母是怎么教您理财的？",
    "财务安全对您意味着什么？",
    "如果能重来，您会在金钱方面做什么不同？",
    "什么是金钱买不到的，但您学会了珍视的？",
    "您为家人的财务未来做的最重要的事是什么？",
    "您希望更早投资的是什么？",
    "慷慨对您意味着什么？",
  ],

  spiritual_beliefs: [
    "您认为人死后会发生什么？",
    "描述一个让您感受到超越自我的力量的时刻。",
    "什么给了您生命的意义？",
    "您的信仰或精神追求是如何随着岁月变化的？",
    "在艰难时刻，哪段祈祷或话语支撑着您？",
    "您认为我们来到这个世界是为了什么？",
    "描述一次您经历了无法解释的事情。",
    "哪种精神修炼或信念对您帮助最大？",
    "您希望孙子孙女们了解您信仰的什么？",
    "苦难教会了您关于生命意义的什么？",
  ],

  fears_and_vulnerabilities: [
    "您最害怕的是什么，您是如何面对它的？",
    "描述一次您真正感到恐惧的经历。",
    "您曾经勇敢面对过的事，是别人可能不知道的？",
    "什么事情让您夜不能寐？",
    "您对下一代最担心的是什么？",
    "您有没有需要原谅自己的事？",
    "有什么是您从未说出口、却一直默默承受着的？",
    "脆弱对您意味着什么？",
    "您最孤独的时刻是什么时候，什么帮助了您？",
    "您希望别人了解您经历过的挣扎是什么？",
  ],
}

export const DAILY_REFLECTIONS_YUE: Record<string, string[]> = {
  early_life: [
    "描述一下你細個時住嘅屋企。唔係佢點樣——而係係一個普通嘅星期二早晨，嗰度係咩氣味？",
    "你細個時瞓房窗外嘅景色係點㗎？",
    "你細個時屋企早餐食咩㗎？係邊個煮㗎？",
    "你上學嘅路係點樣㗎？你記得最深係咩？",
    "你十歲嗰陣最好嘅朋友係邊個？你哋一齊做咩㗎？",
    "你爸爸嘅雙手係點㗎？你對佢哋有咩印象？",
    "你做過嘅第一份工係咩㗎？人工係幾多㗎？",
    "你細個時屋企成日播咩音樂㗎？",
    "年輕時最難受但冇人識講嘅係咩？",
    "邊一道菜能夠即刻帶你返到細個時代？",
  ],

  relationship_to_family: [
    "你媽媽做過咩事，係你自己做咗父母之後先至真正明白㗎？",
    "你爸爸點樣教識你，但係佢從來冇坐低特登教你㗎？",
    "描述一下你知道另一半係啱嘅人嗰個時刻。",
    "你最希望孫仔孫女知道你屋企嘅咩事㗎？",
    "對你嚟講最重要嘅家庭傳統係咩？係點開始㗎？",
    "係家族入面，你最似邊個，又同邊個最唔同㗎？",
    "有冇一句說話，係你希望曾經對一位已故嘅家人講過嘅？",
    "描述一個令你完全出乎意料、你細路仔令你驚喜嘅時刻。",
    "家對你嚟講係點解㗎？",
    "爸爸媽媽給你最好嘅建議係咩㗎？",
  ],

  defining_experiences: [
    "你一生入面最想再經歷一次嘅係哪一日㗎？",
    "描述一下改變咗一切嘅嗰個時刻。唔係大事——而係嗰個靜靜改變咗一切嘅時刻。",
    "描述一件你以為撐唔過去、但最終頂住咗嘅事。",
    "你冒過嘅最大嘅險，係點改變咗你嘅人生㗎？",
    "你人生入面最艱難嘅一年係哪一年？係咩幫你捱過嗰段時間㗎？",
    "描述一次改變咗你嘅旅程——無論係身體上定係心靈上嘅。",
    "你由零開始建立起嚟嘅、令你最感到自豪嘅係咩㗎？",
    "你差啲錯過嘅一個機會係咩㗎？當你把握到嗰陣發生咗咩事？",
    "描述你第一次嚟到一個陌生地方嗰日。",
    "你最慶幸做過嘅一個決定係咩㗎？",
  ],

  professional_philosophy: [
    "你做過嘅最好嘅工係咩㗎？係咩令到佢有意義㗎？",
    "係邊個教識你點樣搏命做嘢㗎？佢畀你睇咗咩㗎？",
    "你職業生涯入面面對過最困難嘅處境係咩㗎？",
    "關於錢，你用咗幾十年先至明白嘅最重要嘅事係咩㗎？",
    "描述一次重要嘅失敗。之後發生咗咩事？",
    "細個時嘅成功同依家嘅成功，喺你眼中有咩唔同㗎？",
    "你職業生涯入面最重要嘅成就係咩㗎？",
    "你共事過最難相處嘅人係邊個㗎？",
    "你會給今日剛踏入職場嘅人咩建議㗎？",
    "做嘢教識咗你關於人生嘅咩事㗎？",
  ],

  core_values: [
    "你持有一個周圍大多數人唔認同嘅信念係咩㗎？",
    "描述一次你做咗啱嘅事，但為此付出咗代價嘅經歷。",
    "有一條底線係你從來都唔會踩過嘅——唔係因為有人話你唔好，而係你內心就係做唔到——嗰係咩㗎？",
    "誠信喺你日常生活入面意味著咩㗎？",
    "爸爸媽媽傳畀你嘅哪種價值觀，係你至今仍然珍視嘅？",
    "你幾時最為自己感到驕傲㗎？",
    "你奉行係點樣對人嘅信念係咩㗎？",
    "有咩係你絕對唔會妥協嘅㗎？",
    "生活教識咗你咩先係真正重要嘅？",
    "你希望人哋點樣記住你㗎？",
  ],

  wisdom_and_lessons: [
    "你收過最好嘅建議係咩㗎？係邊個畀你嘅㗎？",
    "如果可以返到25歲，你最想告訴自己咩㗎？",
    "你見到年輕人常犯咩錯誤，而你已經學識咗點樣避免㗎？",
    "老去最令你感到出奇嘅係咩㗎？",
    "細個時覺得好重要嘅事，依家諗番起根本唔係咁一回事嘅係咩㗎？",
    "你擁有嘅最有價值嘅嘢，但係冇金錢價值嘅係咩㗎？",
    "你會對20歲嘅自己講咩㗎？",
    "隨住年齡增長，你改變咗咩睇法㗎？",
    "長命兼幸福嘅秘訣係咩㗎？",
    "你希望孫仔孫女明白嘅人生道理係咩㗎？",
  ],

  approach_to_people: [
    "你遇到過最有趣嘅人係邊個㗎？係咩令到佢咁特別㗎？",
    "描述一段改變咗你人生嘅友誼。",
    "你係點判斷一個人係咪值得信任㗎？",
    "你識過最善良嘅人係邊個㗎？",
    "描述一個喺其他人都唔信你嗰陣相信你嘅人。",
    "你吃過最大嘅虧，係喺識人方面嘅嗎？嗰係咩教訓㗎？",
    "喺家人以外，邊個對你影響最大㗎？",
    "點樣嘅人先算係好鄰居㗎？",
    "描述一個素不相識嘅人，佢做咗一件令你至今都記得嘅事。",
    "關於人性，你用咗幾十年先至明白嘅係咩㗎？",
  ],

  approach_to_money: [
    "你人生入面第一次存錢買嘅嘢係咩㗎？",
    "描述一段你手頭好緊嘅時光。你係點樣捱過來㗎？",
    "你做過最好嘅財務決定係咩㗎？",
    "你爸爸媽媽係點教你理財嘅㗎？",
    "財務安全對你嚟講意味著咩㗎？",
    "如果可以重嚟，你會喺金錢方面做咩唔同嘅事㗎？",
    "咩係金錢買唔到、但你學識咗去珍惜嘅嘢㗎？",
    "你為屋企人嘅財務未來做過嘅最重要嘅事係咩㗎？",
    "你希望更早投資嘅係咩㗎？",
    "慷慨對你嚟講意味著咩㗎？",
  ],

  spiritual_beliefs: [
    "你覺得人死後會發生咩事㗎？",
    "描述一個令你感受到超越自我嘅力量嘅時刻。",
    "係咩畀咗你生命嘅意義㗎？",
    "你嘅信仰或者精神追求係點樣隨住歲月改變㗎？",
    "係艱難時刻，係咩禱告或者說話支撐著你㗎？",
    "你覺得我哋嚟到呢個世界係為咗咩㗎？",
    "描述一次你經歷咗解釋唔到嘅事情。",
    "哪種精神修煉或者信念對你幫助最大㗎？",
    "你希望孫仔孫女了解你信仰嘅咩嘢㗎？",
    "受苦教識咗你關於生命意義嘅咩嘢㗎？",
  ],

  fears_and_vulnerabilities: [
    "你最驚係咩㗎？你係點面對佢㗎？",
    "描述一次你真係非常恐懼嘅經歷。",
    "你曾經勇敢面對過嘅事，係其他人可能唔知道嘅㗎？",
    "係咩令你瞓唔著覺㗎？",
    "你對下一代最擔心嘅係咩㗎？",
    "你有冇需要原諒自己嘅事㗎？",
    "有咩係你從來都冇講出口、但係一直默默承受著嘅？",
    "脆弱對你嚟講意味著咩㗎？",
    "你最孤獨嘅時刻係幾時㗎？係咩幫助咗你？",
    "你希望人哋了解你經歷過嘅掙扎係咩㗎？",
  ],
}

export function getDailyReflection(
  dimension: string,
  language:  string,
  dayOfYear: number,
): string {
  const library =
    language === 'zh'  ? DAILY_REFLECTIONS_ZH  :
    language === 'yue' ? DAILY_REFLECTIONS_YUE :
                         DAILY_REFLECTIONS_EN
  const questions = library[dimension] ?? library['wisdom_and_lessons']
  return questions[dayOfYear % questions.length]
}

export function getDayOfYear(): number {
  const now   = new Date()
  const start = new Date(now.getFullYear(), 0, 0)
  return Math.floor((now.getTime() - start.getTime()) / (1000 * 60 * 60 * 24))
}
