-- ── Verification surface ──────────────────────────────────────────────────────
-- Spec: BASALITH_VERIFICATION_SURFACE_SKELETON_V3.md section 3, slice 2.3.
--
-- Persists what scripts/coverage-fixture-probe.ts measures against the two
-- fictional demo personas. Until now every drift figure this project has taken
-- existed only in a terminal scrollback, and before slice 2.1 the acceptance
-- transcript did not even capture that. Drift is the number a skeptic would
-- assume was being hidden, so it is the number that has to survive the run.
--
-- Applied by pasting into the Supabase SQL editor. This repo does not run
-- migrations from CI or from the sandbox. Recorded here for the repo history.
--
-- Idempotency: policies use DROP ... IF EXISTS before CREATE rather than the
-- bare CREATE POLICY at 20260502_training_pipeline.sql:35, so a re-paste is a
-- no-op instead of an error. The policy body is identical.
--
-- ── TWO STRUCTURAL RULES, BOTH LOAD BEARING ──────────────────────────────────
--
-- 1. NO FOREIGN KEY TO `archives`, AND NO PATH TO ONE. Not a uuid column that
--    happens to be unconstrained, not a nullable reference, nothing. These
--    tables carry `fixture_id`, a text id for a fictional persona defined in
--    lib/demoPersonas. "A fixture run can never touch customer data" is
--    therefore a fact about the schema rather than a promise about the code, and
--    it stays true even if someone later calls the store with the wrong
--    arguments. The parallel tables for real archives (coverage_runs,
--    coverage_probe_results, archive_coverage) are untouched by this migration.
--
-- 2. NO `verification_coverage` TABLE, DELIBERATELY. The per-domain map is
--    derivable from the probe rows below. A stored second copy would be a thing
--    that can disagree with the rows it was derived from, and when it did,
--    nobody would know which one was wrong. Same reasoning applies to drift: see
--    the note above verification_probe_results.

-- ── Runs ──────────────────────────────────────────────────────────────────────
-- One row per PASS, not per invocation. The fixture probe runs each persona
-- twice so stability can be measured, and the two passes are siblings under one
-- run_group_id with distinct pass_number. Drift is defined across that pair.
CREATE TABLE IF NOT EXISTS verification_runs (
  id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Shared by the passes of one measurement. Generated by the caller, not by the
  -- database, because both passes must agree on it before either row is written.
  run_group_id      UUID        NOT NULL,
  pass_number       INTEGER     NOT NULL CHECK (pass_number >= 1),

  -- A fictional persona id from lib/demoPersonas ('margaret', 'joey'). Text, not
  -- a uuid, and pointing at in-code fiction rather than at any table. See rule 1.
  fixture_id        TEXT        NOT NULL,

  probe_set_version TEXT        NOT NULL,

  -- FALSE until a scheduled run sets it. A manual run writes rows and leaves
  -- them unpublished, so running the probe locally cannot inject rows into the
  -- window the public endpoint aggregates. One code path, one explicit column,
  -- and a local run stays visible internally without reaching the public number.
  published         BOOLEAN     NOT NULL DEFAULT FALSE,

  -- The commit the measured code was at, or NULL when it could not be resolved
  -- honestly. Never a placeholder, never a branch name. A wrong sha beside a
  -- figure is worse than no sha, so the surface renders NULL as unknown.
  commit_sha        TEXT,

  trigger_source    TEXT        NOT NULL DEFAULT 'manual'
    CHECK (trigger_source IN ('manual','cron')),

  started_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finished_at       TIMESTAMPTZ,
  ok                BOOLEAN,
  complete          BOOLEAN,
  error             TEXT,

  probes_total      INTEGER,
  probes_deposit    INTEGER,
  probes_overreach  INTEGER,
  probes_declined   INTEGER,
  probes_errored    INTEGER,
  model_calls       INTEGER
);

-- One row per pass per group. A retried write cannot twin a pass, and a caller
-- cannot accidentally record pass 1 twice under one group.
CREATE UNIQUE INDEX IF NOT EXISTS verification_runs_group_pass
  ON verification_runs (run_group_id, pass_number);

CREATE INDEX IF NOT EXISTS verification_runs_published_idx
  ON verification_runs (published, started_at DESC);

CREATE INDEX IF NOT EXISTS verification_runs_fixture_idx
  ON verification_runs (fixture_id, started_at DESC);

-- Supabase default-grants seven privileges to anon and authenticated at table
-- creation. Repo-wide recon found roughly 1,100 such grants standing, with RLS
-- as the only thing between them and the data. These two tables get both layers
-- from their first day rather than relying on RLS alone.
REVOKE ALL ON verification_runs FROM anon, authenticated;

ALTER TABLE verification_runs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service_role_full_access" ON verification_runs;
CREATE POLICY "service_role_full_access" ON verification_runs
  TO service_role USING (TRUE) WITH CHECK (TRUE);

-- ── Probe results ─────────────────────────────────────────────────────────────
-- One row per probe per pass. 48 probes at probe set v2, two passes, two
-- personas, so a full fixture invocation writes 192 rows.
--
-- DRIFT IS NOT STORED HERE, AND THAT IS THE POINT. It is derived by diffing
-- `basis` per `probe_key` across the two pass_number values inside one
-- run_group_id. See scripts/verification-drift.sql, which is the query the
-- public endpoint will use. Storing a drift integer would create a number that
-- can disagree with the rows it came from, and the whole reason this surface
-- exists is that the figures should be recomputable by anyone holding the rows.
--
-- WHY run_group_id, pass_number, fixture_id AND probe_set_version ARE REPEATED
-- HERE rather than joined from verification_runs. The window query the public
-- endpoint runs is a claim about a number, and it should not depend on a join
-- having been written correctly. All four are written from the same in-memory
-- values that produced the run row, in the same store, so they cannot disagree
-- at write time. run_id stays as the integrity link and the cascade.
CREATE TABLE IF NOT EXISTS verification_probe_results (
  id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id            UUID        NOT NULL REFERENCES verification_runs(id) ON DELETE CASCADE,

  run_group_id      UUID        NOT NULL,
  pass_number       INTEGER     NOT NULL CHECK (pass_number >= 1),
  fixture_id        TEXT        NOT NULL,
  probe_set_version TEXT        NOT NULL,

  domain            TEXT        NOT NULL,
  probe_key         TEXT        NOT NULL,
  basis             TEXT        NOT NULL
    CHECK (basis IN ('deposit','no_position','unsupported')),

  -- TRUE when lib/verifyGrounding.ts returned its catch-path failsafe rather
  -- than an auditor verdict. Excluded from both coverage dimensions: not
  -- evidence in either direction.
  --
  -- THIS COLUMN IS WHY THE RUN ROW AND THE ROW LEVEL DERIVATION CANNOT DISAGREE.
  -- The failsafe writes basis 'unsupported'. runCoverage computes
  -- probes_overreach as `!verifierErrored && basis === 'unsupported'`, excluding
  -- discarded verdicts. A derivation that counted basis='unsupported' off these
  -- rows without this flag would INCLUDE them, so the stored count and the
  -- derived count would diverge silently whenever probes_errored > 0.
  --
  -- That divergence is latent rather than absent: recent runs happen to show
  -- zero errored verdicts, so the two numbers agree by circumstance rather than
  -- by construction, with nothing checking. This column removes the
  -- circumstance. Every per-basis query in scripts/verification-drift.sql
  -- filters on it, and the acceptance gate asserts derived equals stored for
  -- all four runs.
  --
  -- NOT NULL with a default rather than nullable: a null here would be a third
  -- state that means nothing, and row semantics are the irreversible class.
  -- Added before any row existed, so there is no ambiguous history.
  verifier_errored  BOOLEAN     NOT NULL DEFAULT FALSE,

  -- The auditor's one-line reading. When the failsafe fired, lib/coverageRun.ts
  -- writes the literal 'verifier failsafe, verdict discarded' here. That string
  -- is a human-readable message and NOT the carrier of the fact. Read
  -- verifier_errored instead. Recovering a semantic fact by string-matching a
  -- message is not a foundation for a published figure.
  topic             TEXT,

  -- The entity's draft answer. Stored because when a domain reads open, the
  -- answer to "why" is the transcript rather than a number. These are fictional
  -- personas, so nothing here is a real person's material.
  reply             TEXT,

  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- One result per probe per pass. A retried write upserts rather than twinning,
-- which is what keeps the 192 count meaningful.
CREATE UNIQUE INDEX IF NOT EXISTS verification_probe_results_run_probe
  ON verification_probe_results (run_id, probe_key);

-- The index the drift derivation actually walks.
CREATE INDEX IF NOT EXISTS verification_probe_results_group_probe_idx
  ON verification_probe_results (run_group_id, probe_key, pass_number);

-- The per-basis derivation walks this one. Partial, because every per-basis
-- query filters discarded verdicts out, so the index only has to cover the rows
-- those queries can actually return.
CREATE INDEX IF NOT EXISTS verification_probe_results_basis_idx
  ON verification_probe_results (run_id, basis) WHERE NOT verifier_errored;

CREATE INDEX IF NOT EXISTS verification_probe_results_group_domain_idx
  ON verification_probe_results (run_group_id, domain);

REVOKE ALL ON verification_probe_results FROM anon, authenticated;

ALTER TABLE verification_probe_results ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "service_role_full_access" ON verification_probe_results;
CREATE POLICY "service_role_full_access" ON verification_probe_results
  TO service_role USING (TRUE) WITH CHECK (TRUE);

-- ── Comments ──────────────────────────────────────────────────────────────────
COMMENT ON TABLE verification_runs IS
  'One pass of the fixture probe against a fictional demo persona. Carries no foreign key to archives and no path to one, so a fixture run cannot reach customer data by construction.';
COMMENT ON COLUMN verification_runs.run_group_id IS
  'Shared by the passes of one measurement. Drift is defined across the passes of a group.';
COMMENT ON COLUMN verification_runs.published IS
  'FALSE until a scheduled run sets it. A manual or local run must never enter the window the public endpoint aggregates.';
COMMENT ON COLUMN verification_runs.commit_sha IS
  'The commit the measured code was at, or NULL when it could not be resolved. Never a placeholder or a branch name.';
COMMENT ON TABLE verification_probe_results IS
  'One probe verdict per pass. Drift is derived from these rows, never stored. See scripts/verification-drift.sql.';
COMMENT ON COLUMN verification_probe_results.verifier_errored IS
  'TRUE when the grounding verifier returned its catch-path failsafe rather than a verdict. The failsafe writes basis=unsupported, so every per-basis derivation must exclude these rows or it will disagree with the counts on verification_runs.';

-- ── Verification. Run after pasting. ──────────────────────────────────────────
-- Expect two rows, each with rls_enabled = true.
SELECT c.relname AS table_name,
       c.relrowsecurity AS rls_enabled,
       (SELECT count(*) FROM pg_policies p
         WHERE p.schemaname = 'public' AND p.tablename = c.relname) AS policies
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'public'
  AND c.relname IN ('verification_runs','verification_probe_results')
ORDER BY c.relname;

-- Expect ZERO rows. Any row here is a grant that should not exist.
SELECT table_name, grantee, privilege_type
FROM information_schema.role_table_grants
WHERE table_schema = 'public'
  AND table_name IN ('verification_runs','verification_probe_results')
  AND grantee IN ('anon','authenticated')
ORDER BY table_name, grantee, privilege_type;
